spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/one-citations/protocol/openid-connect/certs
logging:
  level:
    org:
      springframework:
        security: debug
